version: '3'
services:
  app:
    build:
      context: .
      target: develop
    tty: true
    container_name: go
    working_dir: /go/src
    volumes:
      - ./src:/go/src
    ports:
      - "3000:3000"

volumes:
  db: